### ISSUE TITLE
Some calls are not displayed

### ISSUE THREAD

**Issue by tarek-eg** [jorgenbuilder/ic-inspector#30]
Hi,
I have noticed that some calls are not displayed after the new upgrade.
For example here on https://app.icpswap.com/swap, when swapping from WICP to XTC the network tab displays all the calls but not registered in the decoder tab.
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/30959956/189510521-bcc81055-6d3d-4bdb-80b1-e4b39d644862.png">

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/30959956/189510528-25653334-781b-4661-b4fa-befb4ee0fb9c.png">

Thanks

**Comment by jorgenbuilder** [comment]
Thanks for the report! What I see when performing a swap *seems* to correspond to the network graph. This is trivial, but it's worth noting that you must have opened the Ic Inspector tab for capture to begin. Is it possible that's the cause of the behaviour you're seeing?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/60938577/198156557-cddcca05-7c36-421f-892e-ab357290bfb9.png">

**Comment by jorgenbuilder** [comment]
I decided to look a bit deeper at this today, since I'd noticed a similar pattern of IC message calls that appear to be missing when using Plug. The reason certain calls appear to be missing is that Plug wallet executes IC messages in a separate background process, not in the main browser process. This is why the calls are missing from the network tab as well, not just the IC Inspector tab.

You can find the missing calls by inspecting the background process of the Plug chrome extension. Navigate to `chrome://extensions/` and click:

![Group 1 (12)](https://user-images.githubusercontent.com/60938577/200963609-b7eb7708-8d0d-40b5-ac0b-d1c856ac1d1a.png)

You jump over to the IC Inspector tab, and now you'll be able to see all the messages that Plug is handling:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60938577/200964309-e2b8fab3-ba14-4171-a91d-458eaf1b0adc.png">

@tarek-eg hope that helps!
