### ISSUE TITLE
Feature request: support site access on click

### ISSUE THREAD

**Issue by paulyoung** [jorgenbuilder/ic-inspector#32]
All of the extension I use support the following option, but ic-inspector doesn't provide it.

![Screen Shot 2022-12-13 at 5 00 33 PM](https://user-images.githubusercontent.com/84700/207478656-8ff0bbf2-8f73-44a9-870c-ff2d5fe5cc97.png)

I like this feature because it allows me to opt-in to when an extension can access pages I'm browsing to. The alternative is to enable and disable the extension, which is less convenient.

**Comment by jorgenbuilder** [comment]
Thanks for the report Paul (and for bringing it to my attention on the dev call today!) I'll have a look at how to add this feature.

**Comment by jorgenbuilder** [comment]
So, extension permissions are... weird. This extension has never requested any explicit permissions, as you can see in [the manifest file's empty permissions array](https://github.com/jorgenbuilder/ic-inspector/blob/main/src/manifest.json#L6).

I've identified that I can achieve the  interface in your screenshot by _adding_ the `<all_urls>` host permission to the manifest, but it doesn't seem to affect the functioning of the extension in any way, even if it is apparently being restricted:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60938577/211126767-0a993fa8-e463-406d-95a9-23f62946be20.png">

_Notice that no access has been granted to the extension, but it's capturing messages in devtools._ 

My interpretation here is that ic inspector has no access to your data whatsoever, until you open up it's specific tab in devtools. Here's a screenshot using the current production permissions, where we can see the extension never gets access to the active tab:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/60938577/211126998-3e8f0c96-8f2c-4b38-8606-65f12757a22d.png">

I might be missing something here, since I don't have a lot of experience with extensions. As far as I can tell though, I have the most restrictive permissions possible (i.e. no permissions at all) and so it's frustrating that this is what people see when they check which permissions the extension requires: 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/60938577/211127132-a30b0067-17ac-47fb-b48f-42858fdff938.png">

**Comment by paulyoung** [comment]
Thanks for looking into it!
